commands:
  page1:
    bal: "/bal 値段を確認します"
    mbal: "/mbal 銀行の値段を確認します /mbal (d or w) (金額) 引き出し(w)、預ける(d)、ことができます"
    warp: "/warp (場所) 指定した場所に3秒後にテレポートします"
    server: "/server (サーバー) 指定したサーバーにテレポートします"
    ar: "/ar (check) (ランク名) 次のランクの条件の確認ができます"
    mmail: "/mmail メールを表示します 詳しくは/mmail help"




show1:
  first:  #最初の文字(String)
    txt: "test"
    subtxt: "ttest"
    loc:
  kaisuu: 3 #紹介回数(Int)
  title: 3 #titleの表示時間(Int、数字/tick)
  fadein: 10 #fadeinの時間(Int、数字/tick)
  fadeout: 10 #fadeoutの時間(Int、数字/tick)
  last: #最後の文字(String)
    txt: "tst"
    subtxt: "ts"
    loc:
  0:
    txt: "txt"
    subtxt: "subtxt"
    loc:
  1:
    txt:
    subtxt:
    loc:

show2:
  first:  #最初の文字(String)
    txt: "test"
    subtxt: "ttest"
    loc:
  kaisuu: 3 #紹介回数(Int)
  title: 3 #titleの表示時間(Int、数字/tick)
  fadein: 10 #fadeinの時間(Int、数字/tick)
  fadeout: 10 #fadeoutの時間(Int、数字/tick)
  last: #最後の文字(String)
    txt: "tst"
    subtxt: "ts"
    loc:
  0:
    txt: "txt"
    subtxt: "subtxt"
    loc:
  1:
    txt:
    subtxt:
    loc:



